config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render new_restaurant_path
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show.html.erb'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to restaurants_path, class: "navbar-brand" do %>
    <%= image_tag "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flogos-world.net%2Fwp-content%2Fuploads%2F2020%2F11%2FYelp-Logo.png&f=1&nofb=1" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item dropdown">
        <%= link_to new_restaurant_path do %>
        <i class="fas fa-plus size"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <% @restaurants.each do |restaurant| %>
    <div class="card-trip">
      <%= image_tag "https://source.unsplash.com/featured/?food-drink,#{restaurant.category}&#{rand(500)}" %>
      <div class="card-trip-infos">
        <div>
          <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
          <p><%= restaurant.address %></p>
          <p><%= restaurant.phone_number %></p>
        </div>
        <h2 class="card-trip-pricing"><strong><%= restaurant.category %></strong></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORIES, include_blank: false %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
<h3><%= @restaurant.name %></h3>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.rating %> <%= review.content %> <%= link_to review_path(review), method: :delete, data: {confirm: "Are you sure?"} do %><i class="fas fa-trash-alt"></i><% end %></li>
    <% end %>
</ul>
<%= link_to restaurants_path do%><i class="fas fa-home"></i><% end %>
<%= link_to new_restaurant_review_path(@restaurant) do %><i class="fas fa-pencil-alt"></i><% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <div class="star-rating">
  <% 5.times do |i| %>
    <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
  <% end %>
  </div>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>